three/config/routes.rb
Rails.application.routes.draw do
  root 'user#create'
  get '/home', to:'hp#home'
  post '/login',to:'user#login'
  get '/new',to:'user#new'
  get '/aaa',to:'hp#aaa'
  get '/info',to:'hp#info'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

three/app/models/user.rb
class User < ApplicationRecord
end

three/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def home
  	
  end
 
end

three/app/controllers/hp_controller.rb
class HpController < ApplicationController
  def home

  end
end

three/app/controllers/user_controller.rb
class UserController < ApplicationController
  def login
   kari = User.find_by(name: params[:session][:name])
   		if kari.password==params[:session][:password]
   			$user = kari
  end
redirect_to home_path

end
def new
	end

  def create
  end
end

three/app/helpers/hp_helper.rb
module HpHelper
end

three/app/helpers/user_helper.rb
module UserHelper
end

three/app/views/hp/aaa.erb
       <div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 cover-img" style="background-image:url('http://free-illustrations-ls01.gatag.net/images/lgi01a201406170900.jpg'); margin-top:90px;">
			<div class="cover-text text-center">
				<p style="color: #f5f5f5;  font-weight:bold;">Academy.Code一期生募集開始<br />
				プログラミングを学ぶ環境はここにある
				</p>
			</div>
		</div>
	</div>
</div>

 
      
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                	DMM.sharebike
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="http://www.dmm.com/">aaa</a>
                    </li>
                    <li>
                       <a href="http://www.dmm.com/">DMM.com</a>
                    </li>
                    <li>
                       <li><%= link_to "お問い合わせ",   info_path %></li>
                    </li>
                    
                    </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Section -->


    <!-- About Section -->
    <section id="about" class="about-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 back" style="background-image:url('http://photoshopvip.net/wp-content/uploads/2012/06/howto2.jpg');">
                    <h1>Codeとは</h1>
                    <h3>プログラミングを本気で学びたいと思う方に場所、仲間、生活資金を提供します。<br />その他いろいろーー</h3>
                </div>
            </div>
        </div>
    </section>

    <!-- Services Section -->
    <section id="services" class="services-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>待遇</h1><br />
                    <table class="taiguu">
                    <tr>
                     <td><div class="col-lg-4 eena" >
                    <%= image_tag("office.png",:class => "eena")  %>
                    
                    </div></td>
                     <td><div class="col-lg-4 eena">
                     <%= image_tag("person.png",:class => "eena")  %>
                     
                     	

                     </div></td>
                     <td><div class="col-lg-4 eena">
                     <%= image_tag("money.png",:class => "eena")  %>
                     	

                     </div></td>
                     </tr>
                     <tr>
                     <td>六本木オフィス無料使用</td>
                     <td>同じ志を持った仲間</td>
                     <td>最低限の生活ができるお金</td>
                     </tr>
                     </table>

                    


                     
                     
                </div>

               

            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>募集要項</h1>
                    <table class="bosyuu" style="margin:auto; font-size:14pt;">
                        <tr>
                            <td>18~30歳の方</td>
                        </tr>
                        <tr>
                            <td>週40時間以上確保できる方</td>
                        </tr>
                        <tr>
                            <td>その他いろいろ</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </section>

    <!-- oubo-section -->
    <section id="oubo" class="oubo-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>応募フォーム</h1>
                  



                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Scrolling Nav JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/scrolling-nav.js"></script>

</body>





<% if $user!=nil %>
	ようこそ<%= $user.name %>さん
	<% end %>

three/app/views/hp/home.html.erb
       <div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 cover-img" style="background-image:url('http://free-illustrations-ls01.gatag.net/images/lgi01a201406170900.jpg'); margin-top:90px;">
			<div class="cover-text text-center">
				<p style="color: #f5f5f5;  font-weight:bold;">Academy.Code一期生募集開始<br />
				プログラミングを学ぶ環境はここにある
				</p>
			</div>
		</div>
	</div>
</div>

 
      
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                	<%= image_tag("logo.png",:size=> "60x60")  %>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a class="page-scroll" href="#page-top" ></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">Codeとは</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">待遇</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">募集要項</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#oubo">応募</a>
                    </li>
                    </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Section -->


    <!-- About Section -->
    <section id="about" class="about-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 back" style="background-image:url('http://photoshopvip.net/wp-content/uploads/2012/06/howto2.jpg');">
                    <h1>Codeとは</h1>
                    <h3>プログラミングを本気で学びたいと思う方に場所、仲間、生活資金を提供します。<br />その他いろいろーー</h3>
                </div>
            </div>
        </div>
    </section>

    <!-- Services Section -->
    <section id="services" class="services-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>待遇</h1><br />
                    <table class="taiguu">
                    <tr>
                     <td><div class="col-lg-4 eena" >
                    <%= image_tag("office.png",:class => "eena")  %>
                    
                    </div></td>
                     <td><div class="col-lg-4 eena">
                     <%= image_tag("person.png",:class => "eena")  %>
                     
                     	

                     </div></td>
                     <td><div class="col-lg-4 eena">
                     <%= image_tag("money.png",:class => "eena")  %>
                     	

                     </div></td>
                     </tr>
                     <tr>
                     <td>六本木オフィス無料使用</td>
                     <td>同じ志を持った仲間</td>
                     <td>最低限の生活ができるお金</td>
                     </tr>
                     </table>

                    


                     
                     
                </div>

               

            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>募集要項</h1>
                    <table class="bosyuu" style="margin:auto; font-size:14pt;">
                        <tr>
                            <td>18~30歳の方</td>
                        </tr>
                        <tr>
                            <td>週40時間以上確保できる方</td>
                        </tr>
                        <tr>
                            <td>その他いろいろ</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </section>

    <!-- oubo-section -->
    <section id="oubo" class="oubo-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>応募フォーム</h1>
                  



                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Scrolling Nav JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/scrolling-nav.js"></script>

</body>





<% if $user!=nil %>
	ようこそ<%= $user.name %>さん
	<% end %>

three/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Three</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
          


  <body>
  

    
  
    <%= yield %>
   
  </body>
</html>

three/app/views/user/create.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Scrolling Nav - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/scrolling-nav.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a class="page-scroll" href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Services</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Section -->
    <section id="intro" class="intro-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Scrolling Nav</h1>
                    <p><strong>Usage Instructions:</strong> Make sure to include the <code>scrolling-nav.js</code>, <code>jquery.easing.min.js</code>, and <code>scrolling-nav.css</code> files. To make a link smooth scroll to another section on the page, give the link the <code>.page-scroll</code> class and set the link target to a corresponding ID on the page.</p>
                    <a class="btn btn-default page-scroll" href="#about">Click Me to Scroll Down!</a>
                </div>
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section id="about" class="about-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>About Section</h1>
                </div>
            </div>
        </div>
    </section>

    <!-- Services Section -->
    <section id="services" class="services-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Services Section</h1>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Contact Section</h1>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Scrolling Nav JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/scrolling-nav.js"></script>

</body>

</html>

three/app/views/user/new.html.erb
<%= form_for(:session,url:login_path) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :password %>
	<%= f.password_field :password %>
<%= f.submit "ログイン", class: "btn btn-primary" %>
<% end %>